// Code generated by gen.go. DO NOT EDIT.

package rustupinit

import (
	_ "embed"
	
	"github.com/jcbhmr/go-rustup/internal/ezgzip"
)

//go:embed rustup-init.linux-arm64-gnu.gz
var gzippedExecutableBytes []byte

func ExecutableBytes() []byte {
	return ezgzip.MustDecompressBytes(gzippedExecutableBytes)
}
