//go:build ignore

package main

import (
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
)

func main() {
	table := []struct {
		url    string
		output string
		GOOS   string
		GOARCH string
	}{
		{"https://static.rust-lang.org/rustup/dist/aarch64-apple-darwin/rustup-init", "rustup-init.darwin-arm64", "darwin", "arm64"},
		{"https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe", "rustup-init.windows-arm64.exe", "windows", "arm64"},
		{"https://static.rust-lang.org/rustup/dist/aarch64-unknown-linux-musl/rustup-init", "rustup-init.linux-arm64", "linux", "arm64"},
		{"https://static.rust-lang.org/rustup/dist/x86_64-apple-darwin/rustup-init", "rustup-init.darwin-amd64", "darwin", "amd64"},
		{"https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe", "rustup-init.windows-amd64.exe", "windows", "amd64"},
		{"https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-musl/rustup-init", "rustup-init.linux-amd64", "linux", "amd64"},
	}
	gitignore, err := os.Create(".gitignore")
	if err != nil {
		log.Fatal(err)
	}
	defer gitignore.Close()
	for _, t := range table {
		log.Printf("Downloading %s to %s", t.url, t.output)
		func() {
			res, err := http.Get(t.url)
			if err != nil {
				log.Fatal(err)
			}
			defer res.Body.Close()
			if res.StatusCode != http.StatusOK {
				log.Fatalf("unexpected status %d %s", res.StatusCode, res.Request.URL)
			}
			f, err := os.OpenFile(t.output, os.O_CREATE|os.O_WRONLY, 0755)
			if err != nil {
				log.Fatal(err)
			}
			defer f.Close()
			_, err = io.Copy(f, res.Body)
			if err != nil {
				log.Fatal(err)
			}
		}()

		gitignore.WriteString("!" + t.output + "\n")

		name := "rustup-init_" + t.GOOS + "_" + t.GOARCH + ".go"
		log.Printf("Generating %s", name)
		err := os.WriteFile(name, []byte(`// Code generated by "go run ./gen.go". DO NOT EDIT.

package main

import _ "embed"

//go:embed `+t.output+`
var rustupInit []byte
`), 0644)
		if err != nil {
			log.Fatal(err)
		}
	}
}
